conda-forge/status

- index.html
- migrator.js
- template.html
Adds migrator status to the page.
> Migrator Status

- migrator.js
closes #36 CC @mariusvniekerk @CJ-Wright 
also fixes the bar being too long
> Some UI fixes

- template.html
merge after compiler migration is complete
> new status message for complete error migration

- migrator.js
Some updates to make the migrations more readable.
> make migrations more readable

- index.html
- template.html
It might be nice for people to be able to find things quicky
> include bot status

- index.html
- template.html
> move status up

- index.html
- template.html
> ENH add github actions usage to status page

- migrator.js
This PR adds migration graphs (optionally, on click) to the visualization
> Migration graph graph

- actions.js
- index.html
- template.html
This PR adds viz for the actions usage!
I ripped code from the migrations and I went ahead with Chart.js for the main viz. The documentation is not great, but it does the work.
> ENH added viz for actions

- actions.js
- index.html
- template.html
This PR adds more graphs to the status page.
> ENH enable more graphs

- cistatus.js
- index.html
- template.html
This PR closes #65. 
I could get 
I could not get
> ENH make the status live!

- actions.js
- cistatus.js
- index.html
- repostatus.js
- template.html
The travis outage revealed bugs. The changes here should fix things.
> BUG make page more robust

- azure.js
- linter.js
> REF separate endpointsa

- actions.js
- index.html
- template.html
This PR adds the usage for the rest of the providers (appveyor, circleci and drone).
> ENH add the rest of the provider usages

- site/migrator.js
This PR adds stable ordering of migrations.
Closes #49
> ENH stable ordering of migrations

- site/template.html
> ENH add admin migrations

- site/template.html
- site/version.js
This PR adds version updates status to the page. 
Screenshots:
> ENH added version updates status

- site/template.html
This PR adds links for the section headings.
> ENH add links to headers

- site/linter.js
- site/migrator.js
This PR makes the status entries explicit. It also adds code to link to migrations.
> ENH link to migrations and support specific statuses

- site/migrator.js
> ENH do the thing

- site/cdn-clone.js
> ENH show the time

- site/template.html
> ENh move docs to actions

- site/migrator.js
- site/template.html
This PR adds separate sections. The recently closed one is not yet active. They can be clicked to hide them to make things more navigable.
cc @CJ-Wright @ocefpaf
> ENH add separate sections for various kinds of migrations

- site/migrator.js
- site/template.html
> ENH add closed migrations

- site/version.js
> Provide direct url to meta.yaml for bad versions

- site/actions.js
- site/template.html
I was looking at https://conda-forge.org/status/#version_updates and notice the typo.
> Fix typo: piplines -> pipelines

- site/actions.js
- site/azure.js
- site/linter.js
This PR points our status page at the new app for status monitoring. It is not on the same heroku server as everything else.
> ENH point status page at new app

- site/cistatus.js
- site/template.html
> Add Anaconda status

- site/template.html
> ENH change link to new bot location

- site/migrator.js
- site/template.html
> REF try this for migration listing
